[tool.black]
extend-exclude = '(__init__.py|setup.py)'

[tool.docsig]
check-property-returns = true
check-overriden = true
check-class = true
# This ignores *pargs, or positional args, to functions
# Most of these are from docassemble's API
ignore-args = true
ignore-kwargs = true
disable = [
  "E113"
]

[tool.mypy]
# global options
exclude = '''(?x)(
    ^setup.py$
  )'''

# per-module options:
[[tool.mypy.overrides]]
module = "docassemble.webapp.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "docassemble.base.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pycountry"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "backports.*"
ignore_missing_imports = true
